FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app_factory.py .
COPY checkout_service ./checkout_service

EXPOSE 8001

CMD ["uvicorn", "checkout_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
